=begin
#CircleCI API

#This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CircleCi::SchedulescheduleidTimetable
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SchedulescheduleidTimetable' do
  before do
    # run before each test
    @instance = CircleCi::SchedulescheduleidTimetable.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SchedulescheduleidTimetable' do
    it 'should create an instance of SchedulescheduleidTimetable' do
      expect(@instance).to be_instance_of(CircleCi::SchedulescheduleidTimetable)
    end
  end
  describe 'test attribute "per_hour"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hours_of_day"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "days_of_week"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["TUE", "SAT", "SUN", "MON", "THU", "WED", "FRI"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.days_of_week = value }.not_to raise_error
      # end
    end
  end

end
