=begin
#CircleCI API

#This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'

# Unit tests for CircleCi::ContextApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContextApi' do
  before do
    # run before each test
    @instance = CircleCi::ContextApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContextApi' do
    it 'should create an instance of ContextApi' do
      expect(@instance).to be_instance_of(CircleCi::ContextApi)
    end
  end

  # unit tests for add_environment_variable_to_context
  # Add or update an environment variable
  # Create or update an environment variable within a context. Returns information about the environment variable, not including its value.
  # @param context_id ID of the context (UUID)
  # @param env_var_name The name of the environment variable
  # @param [Hash] opts the optional parameters
  # @option opts [EnvironmentvariableEnvvarnameBody] :body 
  # @return [InlineResponse2002]
  describe 'add_environment_variable_to_context test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_context
  # Create a new context
  # @param [Hash] opts the optional parameters
  # @option opts [ContextBody] :body 
  # @return [Context]
  describe 'create_context test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_context
  # Delete a context
  # @param context_id ID of the context (UUID)
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'delete_context test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_environment_variable_from_context
  # Remove an environment variable
  # Delete an environment variable from a context.
  # @param env_var_name The name of the environment variable
  # @param context_id ID of the context (UUID)
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'delete_environment_variable_from_context test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_context
  # Get a context
  # Returns basic information about a context.
  # @param context_id ID of the context (UUID)
  # @param [Hash] opts the optional parameters
  # @return [Context]
  describe 'get_context test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_contexts
  # List contexts
  # List all contexts for an owner.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :owner_id The unique ID of the owner of the context. Specify either this or owner-slug.
  # @option opts [String] :owner_slug A string that represents an organization. Specify either this or owner-id. Cannot be used for accounts.
  # @option opts [String] :owner_type The type of the owner. Defaults to \&quot;organization\&quot;. Accounts are only used as context owners in server.
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @return [InlineResponse200]
  describe 'list_contexts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_environment_variables_from_context
  # List environment variables
  # List information about environment variables in a context, not including their values.
  # @param context_id ID of the context (UUID)
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'list_environment_variables_from_context test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
