=begin
#CircleCI API

#This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'

# Unit tests for CircleCi::InsightsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InsightsApi' do
  before do
    # run before each test
    @instance = CircleCi::InsightsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InsightsApi' do
    it 'should create an instance of InsightsApi' do
      expect(@instance).to be_instance_of(CircleCi::InsightsApi)
    end
  end

  # unit tests for get_all_insights_branches
  # Get all branches for a project
  # Get a list of all branches for a specified project. The list will only contain branches currently available within Insights.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workflow_name The name of a workflow. If not passed we will scope the API call to the project.
  # @return [nil]
  describe 'get_all_insights_branches test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_flaky_tests
  # Get flaky tests for a project
  # Get a list of flaky tests for a given project. Flaky tests are branch agnostic.               A flaky test is a test that passed and faliled in the same commit.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2006]
  describe 'get_flaky_tests test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_job_timeseries
  # Job timeseries data
  # Get timeseries data for all jobs within a workflow.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :timeseries_granularity The granularity for which to query timeseries data.
  # @option opts [DateTime] :start_date Include only executions that started at or after this date. This must be specified if an end-date is provided.
  # @option opts [DateTime] :end_date Include only executions that started before this date. This date can be at most 90 days after the start-date.
  # @return [InlineResponse2004]
  describe 'get_job_timeseries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_org_summary_data
  # Get summary metrics with trends for the entire org, and for each project.
  # Gets aggregated summary metrics with trends for the entire org.                Also gets aggregated metrics and trends for each project belonging to the org.
  # @param org_slug Org slug in the form &#x60;vcs-slug/org-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :reporting_window The time window used to calculate summary metrics.
  # @option opts [Object] :project_names List of project names.
  # @return [InlineResponse2005]
  describe 'get_org_summary_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_job_runs
  # Get recent runs of a workflow job
  # Get recent runs of a job within a workflow. Runs going back at most 90 days are returned. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param job_name The name of the job.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.     Note - Querying all branches is not supported yet.
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [DateTime] :start_date Include only executions that started at or after this date. This must be specified if an end-date is provided.
  # @option opts [DateTime] :end_date Include only executions that started before this date. This date can be at most 90 days after the start-date.
  # @return [InlineResponse20010]
  describe 'get_project_job_runs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_job_metrics
  # Get summary metrics for a project workflow&#x27;s jobs.
  # Get summary metrics for a project workflow&#x27;s jobs. Job runs going back at most 90 days are included in the aggregation window. Metrics are refreshed daily, and thus may not include executions from the last 24 hours. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [BOOLEAN] :all_branches Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :reporting_window The time window used to calculate summary metrics.
  # @return [InlineResponse2009]
  describe 'get_project_workflow_job_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_metrics
  # Get summary metrics for a project&#x27;s workflows
  # Get summary metrics for a project&#x27;s workflows. Workflow runs going back at most 90 days are included in the aggregation window. Metrics are refreshed daily, and thus may not include executions from the last 24 hours. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [BOOLEAN] :all_branches Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :reporting_window The time window used to calculate summary metrics.
  # @return [InlineResponse2007]
  describe 'get_project_workflow_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_runs
  # Get recent runs of a workflow
  # Get recent runs of a workflow. Runs going back at most 90 days are returned. Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting. The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :all_branches Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [String] :page_token A token to retrieve the next page of results.
  # @option opts [DateTime] :start_date Include only executions that started at or after this date. This must be specified if an end-date is provided.
  # @option opts [DateTime] :end_date Include only executions that started before this date. This date can be at most 90 days after the start-date.
  # @return [InlineResponse2008]
  describe 'get_project_workflow_runs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflow_test_metrics
  # Get test metrics for a project&#x27;s workflows
  # Get test metrics for a project&#x27;s workflows. Currently tests metrics are calculated based on 10 most recent workflow runs.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [BOOLEAN] :all_branches Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
  # @return [InlineResponse20012]
  describe 'get_project_workflow_test_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_workflows_page_data
  # Get summary metrics and trends for a project across it&#x27;s workflows and branches
  # Get summary metrics and trends for a project at workflow and branch level.               Workflow runs going back at most 90 days are included in the aggregation window.               Trends are only supported upto last 30 days.               Metrics are refreshed daily, and thus may not include executions from the last 24 hours.               Please note that Insights is not a real time financial reporting tool and should not be used for credit reporting.               The most up to date credit information can be found in Plan Overview in the CircleCI UI.
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :reporting_window The time window used to calculate summary metrics.
  # @option opts [Object] :branches The names of VCS branches to include in branch-level workflow metrics.
  # @option opts [Object] :workflow_names The names of workflows to include in workflow-level metrics.
  # @return [InlineResponse2003]
  describe 'get_project_workflows_page_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_workflow_summary
  # Get metrics and trends for workflows
  # Get the metrics and trends for a particular workflow on a single branch or all branches
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param workflow_name The name of the workflow.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :all_branches Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
  # @option opts [Object] :branches The names of VCS branches to include in branch-level workflow metrics.
  # @return [InlineResponse20011]
  describe 'get_workflow_summary test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_workflow_timeseries
  # Workflow timeseries data
  # If no query parameters are supplied, will return timeseries data for all workflows that have ran on the default branch.                                          When granularity is &#x60;hourly&#x60;, up to 48 hours of timeseries data will be returned. When granularity is &#x60;daily&#x60;, up to 90 days of timeseries data will be returned.                                         Different combinations of branches and workflow-names can narrow the query further:                * All workflows, default branch (default, no query parameters)                           * All workflows, all branches: &#x60;all-branches&#x3D;true&#x60;              * All workflows on specific branch: &#x60;branch&#x3D;feature-branch&#x60;              * A specified workflow, all branches: &#x60;workflow-name&#x3D;build&amp;all-branches&#x3D;true&#x60;,               * A specified branch on a specified workflow: &#x60;workflow-name&#x3D;build&amp;branch&#x3D;feature-branch&#x60;
  # @param project_slug Project slug in the form &#x60;vcs-slug/org-name/repo-name&#x60;. The &#x60;/&#x60; characters may be URL-escaped.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :branch The name of a vcs branch. If not passed we will scope the API call to the default branch.
  # @option opts [BOOLEAN] :all_branches Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
  # @option opts [String] :timeseries_granularity The granularity for which to query timeseries data.
  # @option opts [String] :workflow_name The name of a workflow. If not passed we will scope the API call to the project.
  # @option opts [DateTime] :start_date Include only executions that started at or after this date. This must be specified if an end-date is provided.
  # @option opts [DateTime] :end_date Include only executions that started before this date. This date can be at most 90 days after the start-date.
  # @return [InlineResponse2004]
  describe 'get_workflow_timeseries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
